<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Cjora.SaaS.Sys.Api</RootNamespace>
    <AssemblyName>Cjora.SaaS.Sys.Api</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cjora.SaaS.Crm\Cjora.SaaS.Crm.csproj" />
    <ProjectReference Include="..\Cjora.SaaS.Pm\Cjora.SaaS.Pm.csproj" />
    <ProjectReference Include="..\Cjora.SaaS.Sys\Cjora.SaaS.Sys.csproj" />
  </ItemGroup>

</Project>
